/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT post.cdb */

#define CHIP_6713 1

/*  Include Header Files  */
#include <std.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far LOG_Obj LOG_system;
extern far void CSL_cfgInit();

#ifdef __cplusplus
}
#endif /* extern "C" */
